- test/e2e/example/example_test.go
> remove e2e example case

- pkg/pluginManager/apphttphealthy/agentExecuteTask.go
- pkg/pluginManager/netdns/agentExecuteTask.go
- pkg/pluginManager/netreach/agentExecuteTask.go
> Fixed the error in the statistics of each round of results

- pkg/reportManager/worker.go
> fix only ipv6 grpc client cant connect server

- api/v1/agentServer/models/echo_res.go
- api/v1/agentServer/openapi.yaml
- api/v1/agentServer/server/embedded_spec.go
- cmd/agent/cmd/daemon.go
- pkg/agentDnsServer/appDnsServer.go
- pkg/agentHttpServer/appHttpServer.go
- pkg/agentHttpServer/healthHttpServer.go
- pkg/loadRequest/loadDns/dns.go
- pkg/loadRequest/loadDns/dns_requester.go
- pkg/types/agent_config.go
- test/Makefile
- test/chart-app/templates/app.yaml
- test/chart-app/templates/service.yaml
- test/chart-app/values.yaml
- test/docs/NetDns.md
- test/e2e/apphttphealth/apphttphealth_test.go
- test/e2e/common/constants.go
- test/e2e/common/tools.go
- test/e2e/netdns/netdns_suite_test.go
- test/e2e/netdns/netdns_test.go
> add agent app mode dns server

- pkg/loadRequest/loadDns/dns_test.go
> update unitest dns server address

- .github/workflows/auto-nightly-ci.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-pages.yaml
- docs/mkdocs.yml
- docs/overrides/main.html
- test/e2e/common/tools.go
add doc multiversion for kdoctor
> add doc multiversion for kdoctor

- Makefile
- Makefile.defs
- test/Makefile
- test/e2e/apphttphealth/apphttphealth_suite_test.go
- test/e2e/apphttphealth/apphttphealth_test.go
- test/e2e/common/constants.go
- test/e2e/common/tools.go
- test/e2e/netdns/netdns_suite_test.go
test server 已根据任务名进行了区分，取消每个 suite 进行 test server 安装，降低资源使用，e2e init 后直接安装好 test server
> add e2e test server install

- .github/workflows/auto-release.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-pages.yaml
更改文档根目录为 /root
解耦了website 和chart
> Decoupling chart and website

- cmd/agent/cmd/daemon.go
- pkg/pluginManager/agentTools.go
- pkg/pluginManager/apphttphealthy/agentExecuteTask.go
- pkg/pluginManager/netdns/agentExecuteTask.go
- pkg/pluginManager/netreach/agentExecuteTask.go
- pkg/pluginManager/types/types.go
- pkg/resource/resource.go
执行任务时，才进行 cpu 内存统计，任务结束停止统计，节约资源开销。
> resource stats

- test/e2e/apphttphealth/apphttphealth_test.go
robot cherry pick pr <https://github.com/kdoctor-io/kdoctor/pull/224> to branch release-v0.2,  action <https://github.com/kdoctor-io/kdoctor/actions/runs/6542164663>  , commits e1f140c001f6ad2b85f50292306f834e0a30d79e
> Increase the timeout time for e2e requests

- pkg/k8s/apis/system/v1beta1/common_types.go
- pkg/resource/resource.go
feature #293 
实现报告中统计 cpu 使用平均值
> report resource add mean cpu

- .github/workflows/call-release-pages.yaml
Publish development documents through github actions.
> Publish development documents through github actions.

- pkg/loadRequest/loadHttp/http_requester.go
fix #291 
1.优化 http.request clone 方法
2. 修复 http 客户端 超时问题，因参数单位设置错误，导致超时时间由毫秒变成秒，导致连接池出现管理异常，连接被关闭。
> fix http client timeout param error

- pkg/loadRequest/loadHttp/http_requester.go
> add http trace log

- pkg/lock/lock_debug.go
> add took lock time threshold to 0.5

- charts/README.md
- charts/templates/configmap.yaml
- charts/values.yaml
- pkg/types/types.go
fix #373 
fix configmap field error
> typo: fix configmap field error

- charts/templates/configmap.yaml
> Fix configmap missing fields

- pkg/loadRequest/loadHttp/http_requester.go
fix #385 
httptrace is executed using goroutine and cannot be counted externally. Data race will occur and can only be printed in the form of logs. When the request volume is large, a large number of logs will appear, so trace log is cancelled.
> remove http trace log

- .github/workflows/auto-nightly-ci.yaml
- .github/workflows/call-release-pages.yaml
Modify labels and invalid references
> Modify labels and invalid references

- .github/workflows/call-release-pages.yaml
Supports publishing rc versions of docs to dev
> Supports publishing rc versions of docs to dev

- docs/usage/get-started-kind-zh_CN.md
- docs/usage/get-started-kind.md
> update kind quick start

- charts/README.md
- charts/templates/configmap.yaml
- charts/values.yaml
- pkg/loadRequest/loadHttp/http.go
- pkg/loadRequest/loadHttp/http_requester.go
- pkg/loadRequest/loadHttp/http_test.go
- pkg/pluginManager/apphttphealthy/agentExecuteTask.go
- pkg/pluginManager/netreach/agentExecuteTask.go
- pkg/types/types.go
robot cherry pick pr <https://github.com/kdoctor-io/kdoctor/pull/395> to branch release-v0.2,  action <https://github.com/kdoctor-io/kdoctor/actions/runs/7166358897>  , commits 98d1238afed28363e85b72be9faa994971c9945e
> http client decreases to one connect pool for request

- docs/usage/get-started-kind-zh_CN.md
- docs/usage/get-started-kind.md
> docs: format docs

- Makefile.defs
- cmd/agent/cmd/cert.go
- cmd/agent/cmd/daemon.go
- pkg/agentDnsServer/appDnsServer.go
- pkg/agentHttpServer/appHttpServer.go
- test/Makefile
- test/chart-app/Chart.yaml
- test/chart-app/templates/app.yaml
- test/chart-app/values.yaml
- test/e2e/apphttphealth/apphttphealth_test.go
fix #402
fix #429 
1.Improving server robustness in app mode
2.Optimize some chart values
> Enhance agent robustness in app mode && chart value optimization

- .github/workflows/build-image-ci.yaml
- .github/workflows/call-release-image.yaml
fix #441 
fix #446 
action upload v0.4.0 Error when uploading artifact with duplicate name
> fix ci upload artifact duplicate name

- .github/workflows/auto-release.yaml
robot cherry pick pr <https://github.com/kdoctor-io/kdoctor/pull/464> to branch release-v0.2,  action <https://github.com/kdoctor-io/kdoctor/actions/runs/7345375433>  , commits a79aa66f0ecd8c49ee3242229cd1ef2d52d509d0
> fix ci release

- .github/workflows/auto-release.yaml
- .github/workflows/build-image-base.yaml
- .github/workflows/call-e2e.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-pages.yaml
- .github/workflows/call-trivy.yaml
fix #475 
Rollback the version of the download action to v3 to prevent the download from failing
> Rollback the version of the download action to v3

- .github/workflows/build-image-base.yaml
- .github/workflows/call-e2e.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-image.yaml
- .github/workflows/call-release-pages.yaml
- .github/workflows/lint-chart-readme.yaml
- .github/workflows/lint-golang.yaml
- .github/workflows/lint-yaml.yaml
Rollback the version of the upload action to v3
>  Rollback the version of the upload action to v3

- .github/workflows/auto-cherry-pick.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-pages.yaml
> automatically port the label from the initial cherry-picked PR

- .github/workflows/call-e2e.yaml
- .github/workflows/call-release-image.yaml
- .github/workflows/call-trivy.yaml
> Fix TOOMANYREQUESTS failure in Trivy Action
