kdoctor-io/kdoctor

charts/crds/kdoctor.io_apphttphealthies.yaml
charts/crds/kdoctor.io_netdnses.yaml
charts/crds/kdoctor.io_netreaches.yaml
pkg/k8s/apis/kdoctor.io/v1beta1/apphttphealthy_types.go
pkg/k8s/apis/kdoctor.io/v1beta1/netdns_types.go
pkg/k8s/apis/kdoctor.io/v1beta1/netreach_types.go
pkg/loadRequest/loadDns/dns.go
pkg/loadRequest/loadDns/dns_reporter.go
pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadDns/dns_test.go
pkg/loadRequest/loadHttp/http.go
pkg/loadRequest/loadHttp/http_reporter.go
pkg/loadRequest/loadHttp/http_requester.go
pkg/pluginManager/apphttphealthy/agentExecuteTask.go
pkg/pluginManager/netdns/agentExecuteTask.go
pkg/pluginManager/netreach/agentExecuteTask.go

add latency switch

---

pkg/loadRequest/loadDns/dns_reporter.go
pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadHttp/http_reporter.go
pkg/loadRequest/loadHttp/http_requester.go
pkg/pluginManager/tools/tools.go
test/e2e/apphttphealth/apphttphealth_test.go

fix #91  因为字符串 https 中 包含 http 导致 webhook 判断时 会把 https 判断为 http 
fix #92 关闭 latency 开关后，平均延时为 0 导致任务永久成功

fix apphttphealthy webhhok host and fix miss mean latency

---

.github/workflows/auto-nightly-ci.yaml
.github/workflows/auto-release.yaml
.github/workflows/call-release-changelog.yaml
.github/workflows/call-release-chart.yaml
.github/workflows/call-release-pages.yaml
docs/README-zh_CN.md
docs/README.md
docs/mkdocs.yml
docs/overrides/main.html
test/e2e/common/tools.go

release-v0.1 分支上原本的 mkdocs.yaml 中目录结构如下
```
nav:
- README.md
- Installation:
- Installation: usage/install.md
- Quickly Started: usage/get-started-kind.md
...
```
但是 release-v0.1（原本的bug）在 docs 目录并没有  README.md 文件，渲染为 website 后，总是报错找不到页面。本次修改中，为其添加该 md 文件。同时把 github action 的变更，也同步合入 release-v0.1 分支。

Fix release-v0.1 documentation site bug

---

pkg/loadRequest/loadHttp/http_requester.go

修复任务完成后，依然存在 tcp 连接存活，占用资源 
fix #205

fix after task done ,http client idle connections not close

---

pkg/loadRequest/loadHttp/http_requester.go

原方法将 http body 返回丢弃到io.Discard，拷贝过程消耗内存，浪费资源。
取消 copy 过程，直接不处理 body，将 body 关闭，节约了近一半内存

http client optimizes memory

---

pkg/pluginManager/netdns/agentExecuteTask.go
test/e2e/common/tools.go

fix #227 
计算 成功率时，分母填写错误导致计算结果永远为 1

fix netdns success rate err

---

pkg/pluginManager/agentTools.go
test/docs/AppHttpHealth.md
test/e2e/apphttphealth/apphttphealth_test.go

fix #241 
修复当一轮任务超时后，没有输出报告问题。
原因，当任务超时后，向 channel taskSucceed 中发送任务失败信号，但是在外层的 select 中 走入 ctx.done 的 case 中，因此没有向 channel  taskSucceed 取任务结果的操作，导致上层 卡在向 taskSucceed 输入信号处，导致后续生成报告的操作被 pending，经过分析，在超时处理时，因有 ctx 超时处理的 case，所以不需要taskSucceed发送信号与外层通讯。

fix task timeout no report

---

test/e2e/apphttphealth/apphttphealth_test.go

fix  #223 #222 #165 #146 #96 
以上 issue 皆由 app server 返回过慢导致失败
考虑到 ci 机器性能问题，将用例的超时时间增加一些，提高通过率。

Increase the timeout time for e2e requests

---

pkg/agentDnsServer/appDnsServer.go
pkg/k8s/apis/system/v1beta1/apphttphealthy.go
pkg/k8s/apis/system/v1beta1/netdns.go
pkg/loadRequest/loadDns/dns.go
pkg/loadRequest/loadDns/dns_reporter.go
pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadHttp/http.go
pkg/loadRequest/loadHttp/http_reporter.go
pkg/loadRequest/loadHttp/http_requester.go
pkg/pluginManager/apphttphealthy/agentExecuteTask.go
pkg/pluginManager/netdns/agentExecuteTask.go
pkg/pluginManager/netreach/agentExecuteTask.go
test/Makefile
test/docs/NetDns.md
test/e2e/common/tools.go
test/e2e/netdns/netdns_test.go

fix #95 
原方法：每个并发协程平均分配请求，这样会导致，请求数量大于期望的请求数量，影响结果，如期望发送 15 个请求，10 个并发协程执行，当完成 10 个请求后，剩余 5 个请求被 5 个协程分配，但剩下的 5 个协程没有被分配到 依然会去请求，影响期望结果。
现方法：将请求的数量放入一个 channel 中，每个并发协程去channel 中拿请求的许可，拿到许可才进行请求。

fix: qps is not correct

---

test/e2e/netreach/netreach_test.go
test/e2e/runtime/runtime_test.go

fix #249 
fix #251 
fix #253 
netreach 任务超时时间为 1000ms，在 github ci 上会出现个别请求超时情况，增加超时时间为 3000ms

increase netreach e2e timeout

---

pkg/agentDnsServer/appDnsServer.go
pkg/k8ObjManager/service.go
pkg/types/agent_config.go

1. Added the logic for determining whether the obtained DNS IP address list is empty
2. Get and set the label of the default selected DNS service through the environment variable

[#303]fix-Failed_to_get_the_dns_service_IP_list

---

go.mod
go.sum
pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadHttp/http_requester.go
test/e2e/common/tools.go
test/e2e/netreach/netreach_test.go
vendor/github.com/miekg/dns/client.go
vendor/modules.txt

1.dns client 的 udp 连接不设置 write 和 read 的超时时间，当遇见响应较慢的服务时，最后的请求会超过 deadline时间，导致请求失败
2.防止最后的请求因延迟过高，无法得到返回，添加等待时间，等待最后的返回。

dns client udp connect read and write will not time out

---

pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadHttp/http_requester.go

Add request token sending counter

---

pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadHttp/http_requester.go
pkg/pluginManager/netdns/agentExecuteTask.go
pkg/pluginManager/netreach/agentExecuteTask.go
test/Makefile
test/e2e/apphttphealth/apphttphealth_test.go

1.初始化 netreach target 数组，避免扩容耗时。
2.减少 e2e 环境 woker 避免无用 worker 消耗资源
3.添加 log 用于排障

Add log and optimize e2e environment

---

pkg/apiserver/registry/kdoctor/kdoctorreport/etcd.go

fix #349 
Fix kdoctorreport report creation time being set to zero value.

fix report wrong time

---

charts/README.md
charts/values.yaml
docs/usage/debug-zh_CN.md
docs/usage/debug.md
pkg/loadRequest/loadDns/dns.go
pkg/loadRequest/loadDns/dns_suite_test.go
pkg/loadRequest/loadDns/dns_test.go
pkg/loadRequest/loadHttp/http.go
pkg/loadRequest/loadHttp/http_requester.go
pkg/loadRequest/loadHttp/http_suite_test.go
pkg/loadRequest/loadHttp/http_test.go
pkg/pluginManager/apphttphealthy/agentExecuteTask.go
pkg/pluginManager/apphttphealthy/webhook.go
pkg/pluginManager/netdns/agentExecuteTask.go
pkg/pluginManager/netdns/webhook.go
pkg/pluginManager/netreach/agentExecuteTask.go
pkg/pluginManager/netreach/webhook.go
pkg/types/types.go

Dynamic adjustment of worker count: If the worker count is greater than DefaultConcurrency, use DefaultConcurrency as the worker count. If the worker count is less than DefaultConcurrency, the worker count is equal to the QPS count.

add dynamic request worker number

---

pkg/loadRequest/loadHttp/http_requester.go

fix not read response body can't reuse connect

---

charts/README.md
charts/templates/configmap.yaml
charts/values.yaml
pkg/loadRequest/loadHttp/http.go
pkg/loadRequest/loadHttp/http_requester.go
pkg/loadRequest/loadHttp/http_test.go
pkg/pluginManager/apphttphealthy/agentExecuteTask.go
pkg/pluginManager/netreach/agentExecuteTask.go
pkg/types/types.go

fix #394 
http uses only one worker and one connection pool for requests, netHttpDefaultMaxIdleConnsPerHost parameter is set equal to qps, not configured in the chart

http client decreases to one connect pool for request

---

go.mod
go.sum
pkg/loadRequest/loadDns/dns_requester.go
vendor/github.com/ii2day/connexus/conn.go
vendor/github.com/ii2day/connexus/pool.go
vendor/modules.txt

update connexus to v0.1.10
Fixed the problem of directly discarding the request when the link is not obtained.

update connexus to v0.1.10 && Fixed the problem of directly discarding the request when the link is not obtained.

---

docs/usage/apphttphealthy-zh_CN.md
docs/usage/apphttphealthy.md
docs/usage/netdns-zh_CN.md
docs/usage/netdns.md
docs/usage/netreach-zh_CN.md
docs/usage/netreach.md
pkg/apiserver/registry/kdoctor/kdoctorreport/etcd.go
test/e2e/common/tools.go

fix #443 
The report name format is changed to kind plus name to avoid duplicate task names and duplicate report names.

rename report name is kind + name

---

pkg/loadRequest/loadDns/dns_requester.go
pkg/loadRequest/loadHttp/http_requester.go
test/e2e/netdns/netdns_suite_test.go

fix #449 
fix #456 
Splitting qps into request tokens sent in nanoseconds increases the efficiency of link reuse and reduces resource consumption.

change request token send interval

---

.github/workflows/auto-release.yaml

robot cherry pick pr <https://github.com/kdoctor-io/kdoctor/pull/469> to branch release-v0.2,  action <https://github.com/kdoctor-io/kdoctor/actions/runs/7345533175>  , commits 6ddadec811f7ae12b4f02f9b676d582a7798444a

fix release ci kdoctor-test-server invalid
